[package]
name = "kak-lsp"
version = "12.1.0-snapshot"
authors = ["Ruslan Prokopchuk <fer.obbee@gmail.com>"]
edition = "2018"
license = "Unlicense/MIT"

[dependencies]
clap = "2.33.1"
crossbeam-channel = "0.5.1"
daemonize = "0.4.1"
dirs = "2.0.2"
enum_primitive = "0.1.1"
glob = "0.3.0"
indoc = "1.0.3"
itertools = "0.10.1"
jsonrpc-core = "18.0.0"
libc = "0.2.71"
lsp-types = { version = "0.92.1", features = ["proposed"] }
pulldown-cmark = "0.8.0"
rand = "0.8.4"
regex = "1.3.9"
ropey = "1.2.0"
serde = "1.0.112"
serde_derive = "1.0.112"
serde_json = "1.0.55"
serde_repr = "0.1.7"
sloggers = "2.0.2"
slog-scope = "4.3.0"
slog = { version = "2.5.2", features = ["release_max_level_debug"] }
toml = "0.5.6"
unindent = "0.1.7"
url = { version = "2.1.1", features = ["serde"] }
diffs = "0.4.1"
whoami = "1.1.3"

[profile.release]
lto = true

